### ISSUE TITLE
Is this resize method same as OpenCV?

### ISSUE THREAD

**Issue by lucasjinreal** [royinx/CUDA_Resize#3]
linear or billieaner?

**Comment by royinx** [comment]
It is bilinear interpolation, wrote in README, 
Technically, i modified a bit for speed improvement.
In OpenCV's bilinear is picking hybrid method to handle different cases.

One of the situation is, OpenCV using direct access pixel if the height / width can be exactly divided by the new h and width. 
If new_h/old_h  & new_w / old_w  is integer, they will pick the centre of the block instead of bilerp (Bi - linear interpolation)

For example,  6x6 can be split into 4block , 
|||||||
|---|---|---|---|---|---|
|1|1|1|2|2|2
|1|`1`|1|2|`2`|2
|1|1|1|2|2|2
|3|3|3|4|4|4|
|3|`3`|3|4|`4`|4|
|3|3|3|4|4|4|

> Real example :

```
# dummy data
x = (np.random.rand(1,6,6,3)*100).astype(np.uint8)
print(x.reshape(6,6,3)[:,:,0])
```
[[45 70 95 51 50 54]
 [54 80 23 23 78 55]
 [87 34 98 84  0 67]
 [72 49 63  7 20 93]
 [ 2 19 37 60 40 35]
 [31 20 64  1 66 23]]

```
print(cv2.resize(x[0],(2,2))[:,:,0])
```
[[80 78]
 [19 40]]
```
print(gpu_resize(x,shape=(2,2))[0,0,:,:])
```
[[78 67]
 [48 51]]

---
OpenCV's method is _1x1 convolution_ with _d_ dilation / nearest neighbour.
My method is applying bilerp for **ALL** situation since it will not have big different. It is even more accurate since it is a real  _2x2 convolution_ with _d_ dilation to implement smooth on pixels.
